jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Run test
          command: npm run test.
      - run:
          name: Run build
          command: npm run build
