jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Run test
          command: npm run test
      - run:
          name: Run build
          command: npm run build
